[package]
name = "rusty"
version = "0.1.0"
authors = ["Lars Wrenger <lars@wrenger.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
actix-web = "3.3.2"
actix-rt = "1.1.1"
serde = "1.0.118"
structopt = "0.3.21"
priority-queue = "1.0.3"
rand = "0.7.3"
chashmap = "2.2.2"
