[package]
edition = "2018"
name = "rusty"
version = "0.1.0"
authors = ["Lars Wrenger <lars@wrenger.net>", "Julian Krohne <krohnejulian@yahoo.de>", "Julian Gercke <julian.gercke@gmx.de>"]
description = "High performant battlesnake agents written in rust"
default-run = "rusty"
license = "MIT"

[profile.release]
lto = true
opt-level = 3

[[bin]]
name = "move"
path = "src/move.rs"
test = false

[[bin]]
name = "simulate"
path = "src/simulate.rs"
test = false

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
chashmap = "2.2.2"
rand = {version = "0.8.2", features = ["small_rng"]}
serde = "1.0.121"
serde_json = "1.0.61"
structopt = "0.3.21"
threadpool = "1.8.1"
